project:
  type: website

website:
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Index"
        href: index.qmd
      - section: "Week 0"
        contents:
          - text: "Introduction"
            href: intro.qmd
          - text: "Sneak Peak"
            href: sneak.qmd
      - section: "Week 5"
        contents:
          - text: "L1: Introduction to Speech"
            href: 5_1.qmd
          - text: "L2: Language Identification - Intro"
            href: 5_2.qmd
          - text: "L3: Language Identification - Demo"
            href: 5_3.qmd            

theme:
  light: litera
  dark: cyborg