project:
  type: website

website:
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Index"
        href: index.qmd
      - section: "Week 0"
        contents:
          - text: "Introduction"
            href: intro.qmd
          - text: "Sneak Peak"
            href: sneak.qmd

theme:
  light: litera
  dark: cyborg